# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ title: 'Chicago' }, { title: 'Copenhagen' }])
#   Mayor.create(title: 'Emanuel', city: cities.first)

Product.delete_all

Product.create(id: 1, title: 'Volume 1 Liturgical Music',
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat accumsan lacus adipiscing viverra. Suspendisse potenti. Etiam accumsan urna a dolor ullamcorper consectetur. Maecenas cursus auctor pharetra. Ut in interdum erat. Etiam ultricies porta aliquam. Nullam est lorem, vestibulum in pulvinar eget, mattis quis est. Vestibulum nec eleifend eros. Nam bibendum nulla odio, eget mattis lorem. Suspendisse consequat scelerisque ipsum, et cursus libero dapibus nec. Sed magna lacus, molestie vitae mollis et, sagittis eu enim. Vivamus tellus urna, posuere ut sollicitudin eget, mollis ac odio. Donec ac purus sed ipsum iaculis lacinia." )
Product.create(id: 2, title: 'Volume 2 The Mass',
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat accumsan lacus adipiscing viverra. Suspendisse potenti. Etiam accumsan urna a dolor ullamcorper consectetur. Maecenas cursus auctor pharetra. Ut in interdum erat. Etiam ultricies porta aliquam. Nullam est lorem, vestibulum in pulvinar eget, mattis quis est. Vestibulum nec eleifend eros. Nam bibendum nulla odio, eget mattis lorem. Suspendisse consequat scelerisque ipsum, et cursus libero dapibus nec. Sed magna lacus, molestie vitae mollis et, sagittis eu enim. Vivamus tellus urna, posuere ut sollicitudin eget, mollis ac odio. Donec ac purus sed ipsum iaculis lacinia." )
Product.create(id: 3, title: 'Volume 3 The Nativity',
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat accumsan lacus adipiscing viverra. Suspendisse potenti. Etiam accumsan urna a dolor ullamcorper consectetur. Maecenas cursus auctor pharetra. Ut in interdum erat. Etiam ultricies porta aliquam. Nullam est lorem, vestibulum in pulvinar eget, mattis quis est. Vestibulum nec eleifend eros. Nam bibendum nulla odio, eget mattis lorem. Suspendisse consequat scelerisque ipsum, et cursus libero dapibus nec. Sed magna lacus, molestie vitae mollis et, sagittis eu enim. Vivamus tellus urna, posuere ut sollicitudin eget, mollis ac odio. Donec ac purus sed ipsum iaculis lacinia." )
Product.create(id: 4, title: 'Volume 4 Celebrate Christmas',
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat accumsan lacus adipiscing viverra. Suspendisse potenti. Etiam accumsan urna a dolor ullamcorper consectetur. Maecenas cursus auctor pharetra. Ut in interdum erat. Etiam ultricies porta aliquam. Nullam est lorem, vestibulum in pulvinar eget, mattis quis est. Vestibulum nec eleifend eros. Nam bibendum nulla odio, eget mattis lorem. Suspendisse consequat scelerisque ipsum, et cursus libero dapibus nec. Sed magna lacus, molestie vitae mollis et, sagittis eu enim. Vivamus tellus urna, posuere ut sollicitudin eget, mollis ac odio. Donec ac purus sed ipsum iaculis lacinia." )
Product.create(id: 5, title: 'Volume 5 Lent / Easter',
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat accumsan lacus adipiscing viverra. Suspendisse potenti. Etiam accumsan urna a dolor ullamcorper consectetur. Maecenas cursus auctor pharetra. Ut in interdum erat. Etiam ultricies porta aliquam. Nullam est lorem, vestibulum in pulvinar eget, mattis quis est. Vestibulum nec eleifend eros. Nam bibendum nulla odio, eget mattis lorem. Suspendisse consequat scelerisque ipsum, et cursus libero dapibus nec. Sed magna lacus, molestie vitae mollis et, sagittis eu enim. Vivamus tellus urna, posuere ut sollicitudin eget, mollis ac odio. Donec ac purus sed ipsum iaculis lacinia." )
Product.create(id: 6, title: 'Volume 6 More Liturgical Music',
  description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consequat accumsan lacus adipiscing viverra. Suspendisse potenti. Etiam accumsan urna a dolor ullamcorper consectetur. Maecenas cursus auctor pharetra. Ut in interdum erat. Etiam ultricies porta aliquam. Nullam est lorem, vestibulum in pulvinar eget, mattis quis est. Vestibulum nec eleifend eros. Nam bibendum nulla odio, eget mattis lorem. Suspendisse consequat scelerisque ipsum, et cursus libero dapibus nec. Sed magna lacus, molestie vitae mollis et, sagittis eu enim. Vivamus tellus urna, posuere ut sollicitudin eget, mollis ac odio. Donec ac purus sed ipsum iaculis lacinia." )

Song.delete_all

Song.create(product_id: 1, title: 'All That I Am')
Song.create(product_id: 1, title: 'As I Kneel')
Song.create(product_id: 1, title: 'As I Went A Walking')
Song.create(product_id: 1, title: 'Autumn Days')
Song.create(product_id: 1, title: 'Because The Lord Is')
Song.create(product_id: 1, title: 'Brother Sun, Sister Moon')
Song.create(product_id: 1, title: 'Christ Be Beside Me')
Song.create(product_id: 1, title: 'Christ Be Our Light')
Song.create(product_id: 1, title: 'Do You Really Love Me?')
Song.create(product_id: 1, title: 'Eagle\'s Wings')
Song.create(product_id: 1, title: 'Give Me Joy In My Heart')
Song.create(product_id: 1, title: 'God Made The Rain')
Song.create(product_id: 1, title: 'If I Were A Butterfly')
Song.create(product_id: 1, title: 'If I Were A Mountain')
Song.create(product_id: 1, title: 'Immaculate Mary')
Song.create(product_id: 1, title: 'I Saw The Grass')
Song.create(product_id: 1, title: 'I Watch The Sunrise')
Song.create(product_id: 1, title: 'Servant King')
Song.create(product_id: 1, title: 'Sing A Simple Song')
Song.create(product_id: 1, title: 'Spirit Of God')
Song.create(product_id: 1, title: 'Take Me Lord')
Song.create(product_id: 1, title: 'This Is The Day')
Song.create(product_id: 1, title: 'This Little Light')
Song.create(product_id: 1, title: 'Two Little Eyes')
Song.create(product_id: 1, title: 'Will You Join The Circle')
Song.create(product_id: 1, title: 'Yahweh, I Know')

Song.create(product_id: 2, title: 'Come Into His Presence')
Song.create(product_id: 2, title: 'I Belong To The Family')
Song.create(product_id: 2, title: 'I, The Lord Of Sea And Sky')
Song.create(product_id: 2, title: 'Morning Has Broken')
Song.create(product_id: 2, title: 'Praise Him, Praise Him')
Song.create(product_id: 2, title: 'Where Two Or Three')
Song.create(product_id: 2, title: 'Father, I\'m So Sorry')
Song.create(product_id: 2, title: 'Sometimes I\'m Naughty')
Song.create(product_id: 2, title: 'Clapping Gloria')
Song.create(product_id: 2, title: 'Glory, Glory, Glory To God')
Song.create(product_id: 2, title: 'Alleluia, Listen To Jesus')
Song.create(product_id: 2, title: 'Celtic Alleluia')
Song.create(product_id: 2, title: 'Seek Ye First')
Song.create(product_id: 2, title: 'Blest Are You, Lord God')
Song.create(product_id: 2, title: 'Jesus Took A Loaf Of Bread')
Song.create(product_id: 2, title: 'Take Our Bread')
Song.create(product_id: 2, title: 'Our Father - Estelle White')
Song.create(product_id: 2, title: 'Carribbean - Our Father')
Song.create(product_id: 2, title: 'Echo Our Father')
Song.create(product_id: 2, title: 'Peace I Give To You')
Song.create(product_id: 2, title: 'The Peace Of God')
Song.create(product_id: 2, title: 'Be Still For The Presence')
Song.create(product_id: 2, title: 'Jesus, You\'Re The One')
Song.create(product_id: 2, title: 'My Lord And My God')
Song.create(product_id: 2, title: 'One Bread, One Body')
Song.create(product_id: 2, title: 'This Is My Body')
Song.create(product_id: 2, title: 'I Will Be With You')
Song.create(product_id: 2, title: 'Let There Be Peace')
Song.create(product_id: 2, title: 'One More Step')
Song.create(product_id: 2, title: 'Walk With Me')

Song.create(product_id: 3, title: 'Advent Has Come')
Song.create(product_id: 3, title: 'Light The Advent Candle')
Song.create(product_id: 3, title: 'Ave Maria')
Song.create(product_id: 3, title: 'How Can This Be?')
Song.create(product_id: 3, title: 'Mary, Mary Gentle One')
Song.create(product_id: 3, title: 'Now Tell Us Gentle Mary')
Song.create(product_id: 3, title: 'A Song Of Mary')
Song.create(product_id: 3, title: 'The Angel Gabriel')
Song.create(product_id: 3, title: 'I Saw A Star')
Song.create(product_id: 3, title: 'Just Another Star')
Song.create(product_id: 3, title: 'Little Donkey')
Song.create(product_id: 3, title: 'Mary And Joseph Travelled')
Song.create(product_id: 3, title: 'One Bright Star')
Song.create(product_id: 3, title: 'Star In The Sky')
Song.create(product_id: 3, title: 'Have You Got A Room?')
Song.create(product_id: 3, title: 'Nobody Wants To Know')
Song.create(product_id: 3, title: 'The Inn Is Full')
Song.create(product_id: 3, title: 'There Isn\'T Any Room')
Song.create(product_id: 3, title: 'Do You Hear What I Hear?')
Song.create(product_id: 3, title: 'It Was On A Starry Night')
Song.create(product_id: 3, title: 'Shepherds Sleeping')
Song.create(product_id: 3, title: 'Such Things We Have Seen')
Song.create(product_id: 3, title: 'A Little Child Was Born')
Song.create(product_id: 3, title: 'Away In A Manger')
Song.create(product_id: 3, title: 'Little Baby Boy')
Song.create(product_id: 3, title: 'In A Lowly Stable')
Song.create(product_id: 3, title: 'Little Baby Do Not Cry')
Song.create(product_id: 3, title: 'Little Jesus Sweetly Sleep')
Song.create(product_id: 3, title: 'Rock The Baby')
Song.create(product_id: 3, title: 'Silent Night')
Song.create(product_id: 3, title: 'On The Road To Bethlehem')
Song.create(product_id: 3, title: 'Three Kings')
Song.create(product_id: 3, title: 'Searching, Searching')
Song.create(product_id: 3, title: 'March Of The Kings')
Song.create(product_id: 3, title: 'Let\'s Celebrate')

Song.create(product_id: 4, title: 'A Star Shone Bright')
Song.create(product_id: 4, title: 'Angels We Have Heard')
Song.create(product_id: 4, title: 'Away In A Manger')
Song.create(product_id: 4, title: 'Calypso Carol')
Song.create(product_id: 4, title: 'Come To The Manger')
Song.create(product_id: 4, title: 'Come To The Window')
Song.create(product_id: 4, title: 'Ding Dong Merrily')
Song.create(product_id: 4, title: 'Emmanuel')
Song.create(product_id: 4, title: 'Hark The Herald')
Song.create(product_id: 4, title: 'In The Bleak Midwinter')
Song.create(product_id: 4, title: 'Little Drummer Boy')
Song.create(product_id: 4, title: 'O Come All Ye Faithful')
Song.create(product_id: 4, title: 'O Come, Emmanuel')
Song.create(product_id: 4, title: 'Emmanuel')
Song.create(product_id: 4, title: 'O Little Town')
Song.create(product_id: 4, title: 'On Christmas Night')
Song.create(product_id: 4, title: 'Once In Royal David\'s')
Song.create(product_id: 4, title: 'See Amid The Winter\'s')
Song.create(product_id: 4, title: 'Shepherds Have Left')
Song.create(product_id: 4, title: 'Their Sheep')
Song.create(product_id: 4, title: 'Silent Night')
Song.create(product_id: 4, title: 'Somewhere, Someday')
Song.create(product_id: 4, title: 'Tell Out The Christmas')
Song.create(product_id: 4, title: 'The First Nowell')
Song.create(product_id: 4, title: 'The Holly And The Ivy')
Song.create(product_id: 4, title: 'The Virgin Mary')
Song.create(product_id: 4, title: 'We Three Kings')
Song.create(product_id: 4, title: 'We Wish You A Very')
Song.create(product_id: 4, title: 'Merry Good Christmas')
Song.create(product_id: 4, title: 'What Gift')
Song.create(product_id: 4, title: 'When Children Rule')
Song.create(product_id: 4, title: 'While Shepherds Watch')

Song.create(product_id: 5, title: 'Give Me Joy In My Heart')
Song.create(product_id: 5, title: 'Here Comes Jesus On A Donkey')
Song.create(product_id: 5, title: 'Hooray For Jesus')
Song.create(product_id: 5, title: 'Hosanna, Hosanna')
Song.create(product_id: 5, title: 'Sing Hosanna')
Song.create(product_id: 5, title: 'An Upper Room')
Song.create(product_id: 5, title: 'Blest Are You Lord')
Song.create(product_id: 5, title: 'God')
Song.create(product_id: 5, title: 'Jesus Took A Loaf Of Bread')
Song.create(product_id: 5, title: 'This Is My Body')
Song.create(product_id: 5, title: 'Be Still And Know That I Am God')
Song.create(product_id: 5, title: 'Jesus, I Will Stay With You')
Song.create(product_id: 5, title: 'Jesus Prayed In Gethsemane')
Song.create(product_id: 5, title: 'Because The Lord Is My')
Song.create(product_id: 5, title: 'Be With Me, Lord')
Song.create(product_id: 5, title: 'Father, We Adore You')
Song.create(product_id: 5, title: 'Jesus, Remember Me')
Song.create(product_id: 5, title: 'O Lord, You Are The Centre')
Song.create(product_id: 5, title: 'Servant King')
Song.create(product_id: 5, title: 'Were You There?')
Song.create(product_id: 5, title: 'Alleluia, Alleluia, Give Thanks')
Song.create(product_id: 5, title: 'Children, Join The Celebration')
Song.create(product_id: 5, title: 'He Is Lord')
Song.create(product_id: 5, title: 'Hot Cross Buns')
Song.create(product_id: 5, title: 'Lord Of The Dance')
Song.create(product_id: 5, title: 'Sing To The Mountains')
Song.create(product_id: 5, title: 'This Is The Day')
Song.create(product_id: 5, title: 'What A Wonderful Saviour')

Song.create(product_id: 6, title: 'All Things Bright & Beautiful')
Song.create(product_id: 6, title: 'Amazing Grace')
Song.create(product_id: 6, title: 'As We Come Before You Now')
Song.create(product_id: 6, title: 'Bind Us Together')
Song.create(product_id: 6, title: 'Colours Of Day')
Song.create(product_id: 6, title: 'Fill My House Unto The Fullest')
Song.create(product_id: 6, title: 'Follow Me, Follow Me')
Song.create(product_id: 6, title: 'Freely, Freely')
Song.create(product_id: 6, title: 'Guide Me, O Thou Great')
Song.create(product_id: 6, title: 'He Gave Me Eyes So')
Song.create(product_id: 6, title: 'He\'s Got The Whole World')
Song.create(product_id: 6, title: 'I Will Sing, I Will Sing')
Song.create(product_id: 6, title: 'In The Earth A Small Seed')
Song.create(product_id: 6, title: 'Jerusalem')
Song.create(product_id: 6, title: 'Jesus Thou Art Coming')
Song.create(product_id: 6, title: 'Kum Ba Ya')
Song.create(product_id: 6, title: 'On This School Your Blessing')
Song.create(product_id: 6, title: 'Our God Reigns')
Song.create(product_id: 6, title: 'Peace, Perfect Peace')
Song.create(product_id: 6, title: 'Shine, Jesus Shine')
Song.create(product_id: 6, title: 'Sing It In The Valleys')
Song.create(product_id: 6, title: 'Spirit Of The Living God')
Song.create(product_id: 6, title: 'Suffer Little Children')
Song.create(product_id: 6, title: 'Take My Hands')
Song.create(product_id: 6, title: 'Servant Song')
Song.create(product_id: 6, title: 'Whatsoever You Do')


Format.delete_all
Format.create(id: 1, title: 'Music CD / lyrics on CD')
Format.create(id: 2, title: 'Music CD only')
Format.create(id: 3, title: 'Lyrics on CD only')

FormatProduct.delete_all
FormatProduct.create(product_id: 1, format_id: 1, price: 40.13)
FormatProduct.create(product_id: 1, format_id: 2, price: 25.85)
FormatProduct.create(product_id: 1, format_id: 3, price: 25.85)
FormatProduct.create(product_id: 2, format_id: 1, price: 40.13)
FormatProduct.create(product_id: 2, format_id: 2, price: 25.85)
FormatProduct.create(product_id: 2, format_id: 3, price: 25.85)
FormatProduct.create(product_id: 3, format_id: 1, price: 40.13)
FormatProduct.create(product_id: 3, format_id: 2, price: 25.85)
FormatProduct.create(product_id: 3, format_id: 3, price: 25.85)
FormatProduct.create(product_id: 4, format_id: 1, price: 40.13)
FormatProduct.create(product_id: 4, format_id: 2, price: 25.85)
FormatProduct.create(product_id: 4, format_id: 3, price: 25.85)
FormatProduct.create(product_id: 5, format_id: 1, price: 40.13)
FormatProduct.create(product_id: 5, format_id: 2, price: 25.85)
FormatProduct.create(product_id: 5, format_id: 3, price: 25.85)
FormatProduct.create(product_id: 6, format_id: 1, price: 40.13)
FormatProduct.create(product_id: 6, format_id: 2, price: 25.85)
FormatProduct.create(product_id: 6, format_id: 3, price: 25.85)


# 
